### ISSUE TITLE
check wether dsmr reader receives data Synology docker container

### ISSUE THREAD

**Issue by githubnoobjk** [dsmrreader/dsmr-reader#1058]
I am running logger on a raspberry pi and reader in synoloy docker.
It seems I don't receive data using the API. how to check ?
Because I don't use a usb-cable I assume I don't have to use the usb-drivers 

Before switching to this project I used ser2net to receive data in home assistant. So when it is possible to use that again what should be set under devices in docker-compose.

This is what I have in my docker-compose.yaml

```
version: '3.2'

services:
  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
#    build: .
    image: xirixiz/dsmr-reader-docker
    #:test-latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links:
      - dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
      - ./modules/forward_telegram_to_api.py:/dsmr/dsmr_plugins/modules/forward_telegram_to_api.py
      - ./datalogger:/var/log/supervisor/dsmr_datalogger.log
      - ./dsmr_backend_log:/var/log/supervisor/dsmr_backend.log
      
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - SD_AUTOSTART_MQTT=false
      - SD_AUTORESTART_MQTT=false
      - DSMRREADER_PLUGINS=dsmr_plugins.modules.forward_telegram_to_api
      - DSMRREADER_LOGLEVEL=DEBUG
    ports:
      - 7777:80
      - 7779:443
    #devices:
   #   - /dev/ttyUSB0:/dev/ttyUSB0

#volumes:
#   dsmrdb:
#   dsmrdb_backups:
```
