### ISSUE TITLE
ERR_CONNECTION_REFUSED (achter een reverse proxy)

### ISSUE THREAD

**Issue by MRL-33** [dsmrreader/dsmr-reader#1224]
Ik heb mijn systeem (Raspberry Pi 3B+) ingericht volgens de nieuwe situatie (zie hieronder) en nu kan ik niet meer op de DSMR-Reader website terecht.

Oude situatie
Ik heb in Docker een container DSMR-Reader lopen. Deze is geconfigureerd met docker-compose.
De webpagina was altijd bereikbaar met: 192.168.x.y:7777

Nieuwe situatie
Nu heb ik ook een extra container ([Nginx Proxy Manager](https://nginxproxymanager.com/)) toegevoegd wat als Reverse Proxy fungeert. Poort 80 en 443 zijn geforward naar dit systeem.
De webpagina is nu niet meer bereikbaar met 192.168.x.y:7777
Docker-compose.yaml is niet gewijzigd t.o.v. de oude situatie.

Wat moet ik wijzigen om de webpagina te kunnen bereiken op 192.168.x.y:7777 ?
Heb je nog meer informatie nodig om mijn probleem te begrijpen/op te lossen?

Bestand "docker-compose.yaml"
```
version: '3.8'

##the dashboard is reachable at: http://HOSTNAME:7777
##volume: folder_on_host:folder_inside_container

services:
  dsmrdb:
    image: postgres:12-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=$TZ
      - PG_TZ=$TZ
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links:
      - dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
    environment:
      - TZ=$TZ
      - VIRTUAL_HOST=localhost
      - SD_AUTOSTART_MQTT=false
      - SD_AUTORESTART_MQTT=false
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```

bestand ". env"
```
##enviroment

##timezone
TZ=Europe/Amsterdam

##database
POSTGRES_USER=dsmrreader
POSTGRES_PASSWORD=dsmrreader
POSTGRES_DB=dsmrreader

##Nginx
ENABLE_HTTP_AUTH=false
HTTP_AUTH_USERNAME=
HTTP_AUTH_PASSWORD=
```
