### ISSUE TITLE
docker installation help Synology🙋

### ISSUE THREAD

**Issue by migube** [dsmrreader/dsmr-reader#1674]
### Description

"OperationalError: connection to server at "dsmrdb" (172.18.0.7), port 5432 failed: FATAL:  password authentication failed for user "dsmrreader" 

Hi guys
I updated the yml file (I had to change the volume related info from the demo yml to make it install)

but I can't get the dsmr_reader to connect to the DB...
```
dsmrdb:
    image: postgres:14
    container_name: dsmrdb
    restart: always
    volumes:
      - dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader



dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    depends_on:
      dsmrdb:
        condition: service_healthy
    container_name: dsmr
    links:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dsmr_backups:/app/backups
    environment:
      - TZ=Europe/Amsterdam
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - DUID=1027
      - DGID=100
      - DSMRREADER_ADMIN_USER=admin
      - DSMRREADER_ADMIN_PASSWORD=somethingelse
      - DSMRREADER_LOGLEVEL=WARNING
      - DJANGO_SECRET_KEY=dsmrreader
      - DSMRREADER_SUPPRESS_STORAGE_SIZE_WARNINGS=True
      - DSMRREADER_REMOTE_DATALOGGER_MODE=receiver
      - DJANGO_DATABASE_ENGINE=django.db.backends.postgresql
      - DJANGO_DATABASE_NAME=dsmrreader
      - DJANGO_DATABASE_USER=dsmrreader
      - DJANGO_DATABASE_PASSWORD=dsmrreader
      - DJANGO_DATABASE_HOST=dsmrdb
      - DJANGO_DATABASE_CONN_MAX_AGE=60
```
any ideas?

terminal:
pg_isready -U dsmrreader =>works...

db logs:
![image](https://user-images.githubusercontent.com/3582234/180568085-e53a2c23-58d5-4244-933e-f82d071f4616.png)

tx

### DSMR-reader version

5

### DSMR-reader platform

Docker (e.g. Xirixiz)
