### ISSUE TITLE
Datum blijft "hangen"

### ISSUE THREAD

**Issue by peternijssen** [dsmrreader/dsmr-reader#899]
Hallo Dennis,

Excuus voor de onduidelijke titel. Bij mij worden de grafieken niet weergegeven. Ik heb issue #817 reeds bekeken en toegepast, maar helaas maakt dat geen verschil. Echter merkte ik nu ook dat bij mij de datum vast staat.

Op de dashboard pagina staat: `THURSDAY JANUARY 2ND, 2020  `
Bij de PVOutput pagina staat: `Next export: Jan. 2, 2020, 1:40 p.m.`

Verder wil bij mij de status pagina niet laden (time-out) en bij archief kan ik enkel 2 januari en ouder selecteren.

Ik zie in de database wel records van de afgelopen dagen / maanden worden toegevoegd.

Hopelijk is het een beetje duidelijk. Ik denk dus zelf dat dit komt omdat op de een of andere manier de datum op 2 Januari blijft hangen en hij denkt dat er verder niets is, terwijl dat wel zo is.

Enig idee wat hier het probleem is?

Edit:
Onder `Electricity consumption` zie ik wel maar tot 2 januari staan.
In de database tabel `dsmr_datalogger_dsmrreading` zie ik wel data van vandaag staan.
In de database tabel `dsmr_consumption_electricityconsumption` zie ik maar tot 2 januari staan.

**Comment by dennissiemensma** [comment]
Ik denk dat je het beste debug-logging kunt inschakelen: https://dsmr-reader.readthedocs.io/nl/latest/troubleshooting.html#logging

En daarna kijken in `/var/log/supervisor/dsmr_backend.log`. Wellicht zie je daar dan een melding staan met meer informatie.

**Comment by peternijssen** [comment]
Reeds gedaan. Helaas in geen enkele log ook maar iets van een fout. :(
Ik heb vandaag ook geupdate naar de allerlaatste versie, maar helaas geen verschil.

Andere ideeen waar ik naar kan kijken?

**Comment by dennissiemensma** [comment]
Je zult in dit geval niet op zoek moeten naar een fout, maar meer naar een 'constatering' waardoor die hangt. In debug-logging geeft de applicatie aan wat die doet is en waarom. Grote kans dat er dus iets in staat.

Wat geeft de debug log voor de backend als output?

**Comment by peternijssen** [comment]
Ik zie dat de datum inmiddels is verschoven naar vrijdag 4 januari. Ik denk door van alles wat ik heb geprobeerd, hij weer alles aan het in halen is. Gaat alleen even duren zo te merken.

Mocht het toch niet lukken, dan laat ik het weten. Bedankt voor je hulp in ieder geval!

**Comment by dennissiemensma** [comment]
Wat voor hardware gebruik je? Het verwerken van de metingen zou doorgaans niet zo lang moeten duren, tenzij je op een Pi 1 of 2 ofzo draait.

Je kunt ook even in de database zelf kijken of die uberhaupt voortgang maakt met verwerken:
```
sudo su - postgres
psql dsmrreader

select timestamp from dsmr_datalogger_dsmrreading where processed = false order by timestamp asc limit 10;
```

Als je dat een paar keer doet (en het doorloopt), zou ik verwachten dat die niet op dezelfde blijft hangen.

**Comment by peternijssen** [comment]
Ik zit op een Pi 3B+ geloof ik. Of iets in die trant. Inmiddels ben ik door naar 6 jan, 4 dagen verder.
In de aangegeven tabel staan nog zo'n 2.5 miljoen records op niet processed. Inmiddels lijkt hij ook te blijven hangen, want er gebeurt nog niets. Of ben ik niet geduldig.

Onderstaand de debug log.

```
[2020-02-24 20:10:07,000] WARNING   [!] PVOutput: No data found (yet)
[2020-02-24 20:24:31,839] WARNING   [!] PVOutput: No data found (yet)
[2020-02-24 20:38:49,700] WARNING   [!] PVOutput: No data found (yet)
[2020-02-24 20:54:28,166] WARNING   [!] PVOutput: No data found (yet)
[2020-02-24 21:08:32,953] WARNING   [!] PVOutput: No data found (yet)
[2020-02-24 21:24:00,383] WARNING   [!] PVOutput: No data found (yet)
The current logging level only logs warnings and errors, to reduce I/O. More information can be found here: https://dsmr-reader.readthedocs.io/en/v3/troubleshooting.html#logging
[2020-02-24 21:29:43,079] DEBUG    dsmr_backend.management.commands.dsmr_backend: Starting infinite command loop...
[2020-02-24 21:29:43,087] DEBUG    SP: 1 backend service(s) ready to run
[2020-02-24 21:29:43,088] DEBUG    SP: Running "Generate consumption data" (dsmr_consumption.services.run)
```

2 dagen terug zag ik nog:
```
[2020-02-22 15:42:01,566] DEBUG    Compact: Processed reading: 20462823 @ 2020-01-02 16:14:08+01:00
[2020-02-22 15:42:01,606] DEBUG    Compact: Processed reading: 20462824 @ 2020-01-02 16:14:10+01:00
[2020-02-22 15:42:01,645] DEBUG    Compact: Processed reading: 20462825 @ 2020-01-02 16:14:11+01:00
```

**Comment by dennissiemensma** [comment]
Ik vermoed dat de database van je installatie wat indexes mist. Zonder indexes en miljoenen records is die operatie namelijk heel traag. Dat ik die link niet eerder heb gelegd.

Wil je eens kijken wat de output is op:
```
sudo su - postgres
psql dsmrreader

\dS dsmr_datalogger_dsmrreading
```

En dan vooral het onderste blok van de output, dat zou er zo ongeveer uit moeten zien:
```
Indexes:
    "dsmr_datalogger_dsmrreading_pkey" PRIMARY KEY, btree (id)
    "dsmr_datalogger_dsmrreading_9d090a40" btree (processed)
    "dsmr_datalogger_dsmrreading_timestamp_1f7020d1_uniq" btree ("timestamp")
```

**Comment by peternijssen** [comment]
Daar had ik ook niet aan gedacht 🙈

Ik heb nog een MySQL DB, maar ik kan de vertaalslag wel maken. Ik kom er binnen enkele dagen op terug als ik weer thuis ben.

**Comment by dennissiemensma** [comment]
Prima. Die indexes zouden trouwens automatisch aangemaakt moeten zijn, maar het afgelopen jaar zijn er meerdere gebruikers bij wie die soms niet aangemaakt zijn.

```
USE dsmrreader;

SHOW INDEXES FROM dsmr_datalogger_dsmrreading \G;
```

Verwachting iets als:
```
*************************** 1. row ***************************
        Table: dsmr_datalogger_dsmrreading
   Non_unique: 0
     Key_name: PRIMARY
 Seq_in_index: 1
  Column_name: id
    Collation: A
  Cardinality: 0
     Sub_part: NULL
       Packed: NULL
         Null: 
   Index_type: BTREE
      Comment: 
Index_comment: 
*************************** 2. row ***************************
        Table: dsmr_datalogger_dsmrreading
   Non_unique: 1
     Key_name: dsmr_datalogger_dsmrreading_processed_add8a852
 Seq_in_index: 1
  Column_name: processed
    Collation: A
  Cardinality: 0
     Sub_part: NULL
       Packed: NULL
         Null: 
   Index_type: BTREE
      Comment: 
Index_comment: 
*************************** 3. row ***************************
        Table: dsmr_datalogger_dsmrreading
   Non_unique: 1
     Key_name: dsmr_datalogger_dsmrreading_timestamp_1f7020d1
 Seq_in_index: 1
  Column_name: timestamp
    Collation: A
  Cardinality: 0
     Sub_part: NULL
       Packed: NULL
         Null: 
   Index_type: BTREE
      Comment: 
Index_comment: 

```
